export const userTableData = [
  {
    prop: "name",
    label: "用户名",
    // width: 150,
    isColumn: true, //是否展示为表格列
    isForm: true, //是否展示为表单项
    type: "input", //表单类型
    required: true, //是否必填
    disabled: false, //是否不可编辑
  },
  {
    prop: "date",
    label: "创建日期",
    // width: 120,
    isColumn: true,
    isForm: true,
    type: "date",
    required: false,
    disabled: true,
  },
  {
    prop: "role",
    label: "角色",
    // width: 120,
    isColumn: true,
    isForm: true,
    type: "select",
    required: true,
    disabled: false,
    options: [],
  },
  {
    prop: "gender",
    label: "性别",
    // width: 120,
    isColumn: true,
    isForm: true,
    type: "radio",
    required: false,
    disabled: false,
    options: [
      { label: "1", name: "男" },
      { label: "0", name: "女" },
    ],
  },
  {
    prop: "phone",
    label: "电话",
    // width: 120,
    isColumn: true,
    isForm: true,
    type: "input",
    required: false,
    disabled: false,
  },
  {
    prop: "mail",
    label: "邮箱",
    // width: 150,
    isColumn: true,
    isForm: true,
    type: "input",
    required: false,
    disabled: false,
  },
  {
    prop: "department",
    label: "部门",
    // width: 400,
    isColumn: true,
    isForm: true,
    type: "select",
    defaultValue: "",
    disabled: false,
  },
  {
    prop: "state",
    label: "状态",
    // width: 120,
    isColumn: true,
    isForm: false,
    type: "input",
    required: false,
    disabled: false,
  },
];
