import { Gender } from "@/types/enum";

export const userTableData: Form.FormType[] = [
  {
    prop: "username",
    label: "用户名",
    // width: 150,
    isColumn: true, //是否展示为表格列
    isForm: true, //是否展示为表单项
    type: "input", //表单类型
    required: true, //是否必填
    disabled: false, //是否不可编辑
  },
  {
    prop: "date",
    label: "创建日期",
    // width: 120,
    isColumn: true,
    isForm: true,
    type: "date",
    required: false,
    disabled: true,
  },
  {
    prop: "roleId",
    label: "角色",
    // width: 120,
    isColumn: false,
    isForm: true,
    type: "select",
    required: false,
    disabled: false,
    options: [],
  },
  {
    prop: "roleName",
    label: "角色",
    // width: 120,
    isColumn: true,
    isForm: false,
    type: "select",
    required: false,
    disabled: false,
    options: [],
  },
  {
    prop: "gender",
    label: "性别",
    // width: 120,
    isColumn: true,
    isForm: true,
    type: "radio",
    required: true,
    disabled: false,
    options: [
      { label: Gender.male, name: "男" },
      { label: Gender.female, name: "女" },
    ],
  },
  {
    prop: "phone",
    label: "手机号",
    // width: 120,
    isColumn: true,
    isForm: true,
    type: "phone",
    required: false,
    disabled: false,
  },
  {
    prop: "mail",
    label: "邮箱",
    // width: 150,
    isColumn: true,
    isForm: true,
    type: "mail",
    required: false,
    disabled: false,
  },
  {
    prop: "departmentId",
    label: "部门",
    // width: 400,
    isColumn: true,
    isForm: true,
    type: "select",
    required: false,
    disabled: false,
  },
  {
    prop: "state",
    label: "状态",
    // width: 120,
    isColumn: true,
    isForm: false,
    type: "input",
    required: false,
    disabled: false,
  },
  {
    prop: "password",
    label: "初始密码",
    // width: 120,
    isColumn: false,
    isForm: false,
    type: "input",
    required: false,
    disabled: false,
  },
];
